version: 2

seed:
  
  - name: raw_customers
    columns:
      - name: id
        data_tests:
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null

  - name: raw_customers_delete
    columns:
      - name: id
        data_tests:
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null

  - name: raw_customers_new
    columns:
      - name: id
        data_tests:
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null

  - name: raw_customers_update
    columns:
      - name: id
        data_tests:
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null          

  - name: raw_orders
    data_tests:
      - unique:
          column_name: "(user_id || '~' || order_date)"  
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: user_id
        data_tests:
          - not_null
          - relationships:
              to: ref('raw_customers')
              field: id                
      - name: order_date
        data_tests:
          - not_null
      - name: status
        data_tests:
          - not_null
          - accepted_values:
              values: ['return_pending', 'returned', 'completed', 'placed', 'shipped']

  - name: raw_payments
    data_tests:
      - unique:
          column_name: "(order_id || '~' || payment_method || '~' || amount)"  
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: order_id
        data_tests:
          - not_null         
          - relationships:
              to: ref('raw_orders')
              field: id             
      - name: payment_method
        data_tests:
          - not_null
          - accepted_values:
              values: ['coupon', 'credit_card', 'bank_transfer', 'gift_card']
      - name: amount
        data_tests:
          - not_null      
