version: 2

models:
  - name: customers_delete
    data_tests:
      - unique:
          column_name: "(first_name || '~' || last_name)"  
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: load_type
        data_tests:
          - not_null
          - accepted_values:
              values: ['delete']

  - name: customers_init
    data_tests:
      - unique:
          column_name: "(first_name || '~' || last_name)"
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: load_type
        data_tests:
          - not_null
          - accepted_values:
              values: ['init']

  - name: customers_new
    data_tests:
      - unique:
          column_name: "(first_name || '~' || last_name)"  
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: load_type
        data_tests:
          - not_null
          - accepted_values:
              values: ['new']

  - name: customers_update
    data_tests:
      - unique:
          column_name: "(first_name || '~' || last_name)"  
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: load_type
        data_tests:
          - not_null
          - accepted_values:
              values: ['update']
