version: 2

models:
  - name: customers
    data_tests:
      - unique:
          column_name: "(load_type||'~'||first_name || '~' || last_name)"  
          column_name: "(load_type||'~'||id)"
    columns:
      - name: id
        data_tests:
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: load_type
        data_tests:
          - not_null
          - accepted_values:
              values: ['init', 'new', 'update', 'delete']
      - name: max_delete_count
        data_tests:
          - not_null
          - accepted_values:
              values: [0, 1]      